### ISSUE TITLE
New interpreter error: MEMORY

### ISSUE THREAD

**Issue by qingfeng-zhang** [wklenk/rak8212-espruino-nb-iot#3]
there got some error message " New interpreter error: MEMORY" after we tested your latest version data-logger-bg96-mqtt.js , did anyone meet this problem?

**Comment by wklenk** [comment]
Did you add more code? I think there current code does **not** allow not too much additional code, else you will run into memory limitations. I myself had to "tune" some function names. You could try some things to reduce the memory footprint of the code. Maybe it would help to remove the comments? But yes, memory is a problem, and I would like to have more of it.

**Comment by wklenk** [comment]
I added telemetry messages on memory usage now. Yes, low memory **is** a problem. Please use the "MINIFICATION" feature of the Espruino Web IDE to make the code smaller before transfering to the RAK8212. Made good experiences with "Closure (online)".
